/* APLICANDO ESTRUTURA BASICA, SIMPLES */
CREATE DATABASE TABELA_COPIADA;
USE TABELA_COPIADA;
CREATE TABLE TABELA_1(
ID INT PRIMARY KEY AUTO_INCREMENT
,NOME VARCHAR(50)
,CIDADE ENUM('SÃO PAULO', 'RIO DE JANEIRO')
,CARGO VARCHAR(50) 
);


/* INSERINDO DADOS  NA TABELA */ 
INSERT INTO TABELA_1(NOME, CIDADE) VALUES('JONAS','SÃO PAULO');
INSERT INTO TABELA_1(NOME, CIDADE) VALUES('RICARDO','SÃO PAULO');
INSERT INTO TABELA_1(NOME, CIDADE) VALUES('FABIO','SÃO PAULO');
INSERT INTO TABELA_1(NOME, CIDADE) VALUES('JONATHAS','SÃO PAULO');
INSERT INTO TABELA_1(NOME, CIDADE) VALUES('AGATHA','SÃO PAULO');
INSERT INTO TABELA_1(NOME, CIDADE) VALUES('PEDRO','SÃO PAULO');


/* CRIANDO ESTRUTURA SEMELHANTE, BASICAMENTE VERSIONANDO A TABELA, PODERIA POR UM LEFT JOIN E OUTRAS COISAS, AQUI TAMBEM  */
CREATE TABLE TABELA_2 LIKE TABELA_1;
INSERT INTO TABELA_2 
SELECT * FROM TABELA_1 WHERE CIDADE = 'SÃO PAULO';


/* 
MOSTRANDO COMO AS DUAS TABELAS FICARAM IDENTICAS, NO MERCADO DE TRABALHO COLOCARIAMOS COISAS NOVAS EXEMPLO: LEFT JOIN, WHEREM DISTINCT
MAS AQUI É SO UM EXEMPLO
 */
SELECT * FROM TABELA_2;
SELECT * FROM TABELA_1;
